### ISSUE TITLE
cli: make tests windows compatible

### ISSUE THREAD

**Issue by ernscht** [namics/frontend-defaults#11]
The jest snapshot tests aren't windows compatible.

example:
```
   ".babelrc": {
            "override": false,
    -       "data": "{\\n\\t\\"presets\\": [\\n\\t  \\"env\\"\\n\\t]\\n}"
    +       "data": "{\\r\\n\\t\\"presets\\": [\\r\\n\\t  \\"env\\"\\r\\n\\t]\\r\\n}"
          }
      }
```

**Comment by smollweide** [comment]
I will remove all tabs and line breaks. That should solve this issue

**Comment by smollweide** [comment]
It‘s not related to jest because it‘s the fs.readFile result which is passed into the snapshot

**Comment by ernscht** [comment]
Many tests are still failing.
As an example, patch for build.ts.snap to see what windows expects:
[build_ts_snap.zip](https://github.com/namics/frontend-defaults/files/2890360/build_ts_snap.zip)

**Comment by smollweide** [comment]
Hi @ernscht,
please test it again. I used the api result set maybe this is working for you.

**Comment by ernscht** [comment]
Not completely.
Paths are different under Windows.

```
build › build-with-ts

expect(received).toMatchSnapshot()

Snapshot name: `build build-with-ts 1`

- Snapshot
+ Received

    Array [
    "package.json",
-   "src/index.ts",
+   "src\\index.ts",
    "tsconfig.json",
    ]
```

**Comment by ernscht** [comment]
I could solve the problem with a SnapshotSerializer. This Should work on all platforms. What do you think?

**Comment by ernscht** [comment]
Hey @smollweide - merge ok?

**Comment by ernscht** [comment]
Solving the issue only was possible with the temporary wrong tests.
So back on field one.

**Comment by smollweide** [comment]
Hi @ernscht,
please retest

**Comment by ernscht** [comment]
works perfect, thanks a lot
